---

- name: apt | Install ...
  apt: name={{item}} state=present
  with_items:
    - git
    - rpm

- set_fact:
    nginx_conf: /etc/nginx/sites-available
    supervisor_confdir: /etc/supervisor/conf.d
    supervisor_ext: conf
    supervisor_service: supervisor

